import { Inter } from 'next/font/google'
import './globals.css'

// fonts
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

// components
import Navbar from '@/components/Layout/Navbar'
import Footer from '@/components/Layout/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CodesWear',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className='min-h-svh pt-40 sm:py-16 bg-neutral-800 overflow-x-hidden'>
          {children}
        </main>
        <Footer />
      </body>

    </html>
  )
}
